# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build application and export ipa"
  lane :build do
    gym(scheme: "ComponentsApp1",
        export_options: {
          method: "ad-hoc",
          provisioningProfiles: {
            "com.p.ComponentsApp1" => "Phittaya Wongsuwan"
          }
        },
        output_directory: "./ipa",
        output_name: "ComponentsApp1.ipa")
  end
end
